# Generated by Django 5.2.7 on 2025-11-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='salt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
